services:
  hotel-db:
    image: mysql:8
    container_name: hotelbooking-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: HotelBooking2025!
      MYSQL_DATABASE: hotelbooking_db
      MYSQL_USER: hotel_app
      MYSQL_PASSWORD: HotelApp2025!
    ports:
      - "3306:3306"
    networks:
      - hotelnet
    volumes:
      - hotel_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "hotel_app", "-pHotelApp2025!"]
      timeout: 20s
      retries: 10

  hotel-app:
    build: .
    container_name: hotelbooking-webapp
    restart: always
    ports:
      - "3000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOCKER_ENV=true
      - ConnectionStrings__Default=Server=hotel-db;Port=3306;Database=hotelbooking_db;User Id=hotel_app;Password=HotelApp2025!;TreatTinyAsBoolean=true;AllowPublicKeyRetrieval=True;
    depends_on:
      hotel-db:
        condition: service_healthy
    networks:
      - hotelnet

  hotel-adminer:
    image: adminer
    container_name: hotelbooking-dbadmin
    restart: always
    ports:
      - "9000:8080"
    networks:
      - hotelnet

volumes:
  hotel_mysql_data:

networks:
  hotelnet:
    driver: bridge